AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tresidus AI Backend API

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Environment:
      Variables:
        NODE_ENV: production

Resources:
  TresidusApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda.handler
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref TresidusApiGateway
        RootApiGateway:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref TresidusApiGateway

  TresidusApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

Outputs:
  TresidusApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${TresidusApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/"
    Export:
      Name: TresidusApiUrl
